Fix multithreading usage of template rendering
The call stack of the issue:

java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "this.doctypeLine" is null
        at de.neuland.pug4j.template.PugTemplate.setDoctype(PugTemplate.java:73) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.parser.node.DoctypeNode.execute(DoctypeNode.java:12) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.parser.node.BlockNode.execute(BlockNode.java:32) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.compiler.Compiler.compile(Compiler.java:31) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.template.PugTemplate.process(PugTemplate.java:28) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.PugConfiguration.renderTemplate(PugConfiguration.java:96) ~[pug4j-2.2.0.jar:na]
        at de.neuland.pug4j.spring.view.PugView.doRender(PugView.java:57) ~[spring-pug4j-3.2.0.jar:na]
        at de.neuland.pug4j.spring.view.PugView.renderMergedTemplateModel(PugView.java:28) ~[spring-pug4j-3.2.0.jar:na]
        at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:181) ~[spring-webmvc-6.1.3.jar:6.1.3]
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314) ~[spring-webmvc-6.1.3.jar:6.1.3]